### ISSUE TITLE
Add support for: Inventory Profiles Next

### ISSUE THREAD

**Issue by ghost** [p4rty4nimAl/cachemyenderchest#1]
Hello, the overlay from Inventory Profiles Next is overlapping.
The mod: https://modrinth.com/mod/inventory-profiles-next

**Comment by p4rty4nimAl** [comment]
Hey, thanks for reporting that! I'll try to fix it soon, sorry about the long wait for this reply.

**Comment by p4rty4nimAl** [comment]
Fixed in mod versions above and including 1.0.1, meaning Minecraft versions 1.19.1 and above.

**Comment by ghost** [comment]
Thank you:)
